version: "3.8"
services:
  server:
    build:
      context: ./
      target: server
    ports:
      - "8080:8080"
    command: ["./server"]
  client:
    build:
      context: ./
      target: client
    command: ["./client"]
    depends_on:
      - server
